<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var \Magento\Customer\Block\Form\Login\Info $block
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <h1 id="block-new-customer-heading" class="label-blue font-small" role="heading" aria-level="2"><?php echo $block->escapeHtml(__('New Customers')) ?></h1>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <!-- <div class="field note"><?php echo $block->escapeHtml(__('text')) ?></div> -->
        <p><?php echo $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php echo $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?php echo $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
