<div class="row custom-order">
    <div class="col-md-8 col-xs-7">
        <h2>Custom order</h2>
        <p>Have a fabric you would like us to use? Have a custom Woogie Whomper made!</p>
    </div>
    <div class="col-md-4 col-xs-5">
        <a href="mailto:kathy@woogiewhomper.com?Subject=Woogie%Whomper%-%custom%orders" class="send-email">
            <span>Email</span> 
            <img src="<?php echo $this->getViewFileUrl('images/icon-email-white.png'); ?>" alt=""> 
            <img src="<?php echo $this->getViewFileUrl('images/right-large-arrow.png'); ?>" alt="">
        </a>
    </div>
</div>