<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="<?php echo $this->getUrl('dogs.html'); ?>">Dog</a>
    <a href="<?php echo $this->getUrl('cats.html'); ?>">Cat</a>
    <a href="<?php echo $this->getUrl('15-for-you'); ?>">For You</a>
    <a href="<?php echo $this->getUrl('about-us'); ?>">About Us</a>
    <a href="<?php echo $this->getUrl('faq'); ?>">FAQ</a>
    <a href="<?php echo $this->getUrl('contact-us'); ?>">Contact</a>
    <a href="<?php echo $this->getUrl('engage'); ?>">Engage</a>
</div>
<div class="col-lg-4 col-md-4 col-sm-4 col-xs-2 custom-menu">
    <span class="open-sidenav" onclick="openNav()">
        <img src="<?php echo $this->getViewFileUrl('images/icon-menu.svg'); ?>" class="img-responsive menu-icon" alt="Menu">
    </span>
</div>

<script type="text/javascript">
        /* Set the width of the side navigation to 250px */
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        /* Set the width of the side navigation to 0 */
        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>