<div>
	<div class="container" id="onlineExclusives">
	            <div class="row">
	                <div class="col-lg-12 col-xs-12">
	                    <h2 class="heading">Online Exclusives</h2>
	                    <p class="sub-heading">Limited quantities</p>
	                </div>
	            </div>
	            <div class="row">
	                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
	                    <img src="<?php echo $this->getViewFileUrl('images/peterson.png'); ?>" class="img-responsive center-block">
	                    <img src="<?php echo $this->getViewFileUrl('images/fabric-peterson.png'); ?>" class="img-responsive center-block">
	                    <p class="fabric-name">Peterson</p>
	                </div>
	                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
	                    <img src="<?php echo $this->getViewFileUrl('images/harry.png'); ?>" class="img-responsive center-block">
	                    <img src="<?php echo $this->getViewFileUrl('images/fabric-harry.png'); ?>" class="img-responsive center-block">
	                    <p class="fabric-name">Harry</p>
	                </div>
	                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
	                    <img src="<?php echo $this->getViewFileUrl('images/vector.png'); ?>" class="img-responsive center-block">
	                    <img src="<?php echo $this->getViewFileUrl('images/fabric-vector.png'); ?>" class="img-responsive center-block">
	                    <p class="fabric-name">Vector</p>
	                </div>
	                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	                    <a href="#" class="view-more">see all</a>
	                    <img src="<?php echo $this->getViewFileUrl('images/arrow-see-all.png'); ?>" class="view-more-arrow hidden-xs">
	                    <img src="<?php echo $this->getViewFileUrl('images/arrow-see-all-mob.png'); ?>	" class="view-more-arrow hidden-sm hidden-md hidden-lg">
	                </div>
	            </div>
	</div>
	<div id="freeGift">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 left-content">
                    <h2 class="heading">Free gift Blanket</h2>
                    <p class="sub-heading">Every Woogie Whomper comes with a plush blanket.</p>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 right-img">
                    <img src="<?php echo $this->getViewFileUrl('images/free-gift.png'); ?>" class="img-responsive">
                </div>
            </div>
        </div>
</div>
   
    <div id="chooseOne">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 left-content">
                    <h2 class="heading">Choose one for someone you love!</h2>
                </div>
            </div>
            <div class="row">
                <a><img src="<?php echo $this->getViewFileUrl('images/choose-one-bg.png'); ?>" class="img-responsive"></a>
            </div>
        </div>
    </div>
</div>
