<div class="container" id="footer">
	
            <div class="row top-footer">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="toTop">
                    <p>Top of page</p>    
                </div>
            </div>
            <div class="row main-footer">
                <div class="col-lg-1 col-lg-offset-1 col-md-1 col-md-offset-1 col-sm-1 col-sm-offset-1 col-xs-12">
                    <span class="open-sidenav" onclick="openNav()">
                        <img src="<?php echo $this->getViewFileUrl('images/footer-nav-icon.png'); ?>" class="img-responsive menu-icon hidden-xs">
                    </span>
                    <div class="social-icons-mob hidden-sm hidden-md hidden-lg">
                        <span class="open-sidenav" onclick="openNav()">
                            <img src="<?php echo $this->getViewFileUrl('images/footer-nav-icon.png'); ?>" class="img-responsive">
                        </span>
                        <a href="#"><img src="<?php echo $this->getViewFileUrl('images/footer-facebook.png'); ?>" class="img-responsive"></a>
                        <a href="#"><img src="<?php echo $this->getViewFileUrl('images/footer-insta.png'); ?>" class="img-responsive"></a>
                        <a href="#"><img src="<?php echo $this->getViewFileUrl('images/footer-youtube.png'); ?>" class="img-responsive"></a>
                    </div>
                </div>
                <div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-4 col-md-offset-1 col-xs-12">
                    <div class="social-icons hidden-xs">
                        <a href="#"><img src="<?php echo $this->getViewFileUrl('images/footer-facebook.png'); ?>" class="img-responsive"></a>
                        <a href="#"><img src="<?php echo $this->getViewFileUrl('images/footer-insta.png'); ?>" class="img-responsive"></a>
                        <a href="#"><img src="<?php echo $this->getViewFileUrl('images/footer-youtube.png'); ?>" class="img-responsive"></a>
                    </div>
                    <div class="customer-care">
                        <h4 class="heading">Customer care</h4>
                        <a href="<?php echo $this->getUrl('customer/account'); ?>">My account</a>
                        <a href="<?php echo $this->getUrl('customer/trackorder'); ?>">Track my order</a>
                        <a href="<?php echo $this->getUrl('returns-exchanges'); ?>">Returns &amp; exchanges</a>
                        <a href="<?php echo $this->getUrl('privacy-policy-cookie-restriction-mode'); ?>">Privacy</a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <a href="<?php echo $this->getUrl('for-you'); ?>" class="share-link">Give $15, Get $15. Share.</a>
                    <div class="guarantee">
                        <h4>Our guarantee</h4>
                        <p>Love it, or let us know and we'll make it right. 100% money back guarantee.</p>
                    </div>
                    <a href="mailto:kathy@woogiewhomper.com?Subject=Woogie%Whomper%distributor%opportunities" target="_top" class="send-email-link">Become a distributor</a>
                </div>
            </div>
        
</div>

<script type="text/javascript">
    var $ = jQuery.noConflict();
    $(window).scroll(function() {
        if ($(this).scrollTop()) {
            $('#toTop').fadeIn();
        } else {
            $('#toTop').fadeOut();
        }
    });

    $("#toTop").click(function () {
       //1 second of animation time
       //html works for FFX but not Chrome
       //body works for Chrome but not FFX
       //This strange selector seems to work universally
       $("html, body").animate({scrollTop: 0}, 1000);
    });
</script>