<div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                    
                    <div id="myCarousel" class="carousel home-carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                            <li data-target="#myCarousel" data-slide-to="3"></li>
                            <li data-target="#myCarousel" data-slide-to="4"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                          <div class="item active">
                            <video width="100%" controls>
                              <source src="<?php echo $this->getViewFileUrl('images/home-banner-1.mp4'); ?>" type="video/mp4">
                              <source src="<?php echo $this->getViewFileUrl('images/home-banner-1.ogg'); ?>" type="video/ogg">
                              Your browser does not support HTML5 video.
                            </video>
                          </div>

                          <div class="item">
                            <img src="<?php echo $this->getViewFileUrl('images/home-banner-2.png'); ?>" alt="Chicago" style="width:100%;">
                          </div>

                          <div class="item">
                            <img src="<?php echo $this->getViewFileUrl('images/home-banner-3.png'); ?>" alt="New york" style="width:100%;">
                          </div>
                            <div class="item">
                            <img src="<?php echo $this->getViewFileUrl('images/home-banner-4.png'); ?>" alt="New york" style="width:100%;">
                          </div>
                            <div class="item">
                            <img src="<?php echo $this->getViewFileUrl('images/home-banner-5.png'); ?>" alt="New york" style="width:100%;">
                          </div>
                        </div>

                        <!-- Left and right controls -->
                        <!--<a class="left carousel-control" href="#myCarousel" data-slide="prev">
                          <span class="glyphicon glyphicon-chevron-left"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                          <span class="glyphicon glyphicon-chevron-right"></span>
                          <span class="sr-only">Next</span>
                        </a>-->
                      </div>
                    
                </div>
            </div>
            <div class="row banner-btm-bg">
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                    <p>Bored dog invents a clever toy that also keeps mom happy (well, mostly).</p>
                </div>
            </div>
        </div>
    </div>
