<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
$modal_code = '';
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?> row products ">
        <div class="col-md-12 heading">Choose your Woogie Whomper below!</div>
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
            <div class="product-item-info col-md-6 col-sm-6 " data-container="product-grid">
                <div class="product-img">
                    <?php //echo "<pre>". print_r($_product, true); exit;?>
                    <?php $productImage = $block->getImage($_product, $image); ?>
                    <?php // Product Image ?>
                    <?= $productImage->toHtml() ?>
                    <a id="image-modal-<?php echo $_product->getId(); ?>" href="#" class="zoom-icon hidden-xs" type="button" >
                        <img src="<?php echo $this->getViewFileUrl('images/icon-product-zoom.png'); ?>" alt="">
                    </a>
                </div>
                <h4 class="title">
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"> 
                        <?php
                            echo $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                    </a>
                </h4>
                <p class="product-info">
                    <?php 
                    /* @escapeNotVerified */ $product_description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ;
                        $product_price = $_helper->productAttribute($_product, $_product->getPrice(), 'price');
                        $product_price = $block->stripTags($product_price, null, true);
                        //$product_price = round($product_price, 2);

                        $pro_qty = $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());

                        $reviewFactory->getEntitySummary($_product, $_product->getStore()->getWebsiteId());

                        $ratingSummary = $_product->getRatingSummary()->getRatingSummary();

                        echo $product_description = $block->stripTags($product_description, null, true);
                    ?>
                  
                    <br>
                    <?php  /* @escapeNotVerified */ echo "$".round($product_price, 2); ?> | <?php echo $pro_qty; ?> left | 3 people looking | <?php if($ratingSummary) : echo $ratingSummary. "stars"; endif; ?> 
                    <br>
                    <a href="javascript:void()" onclick="add_to_cart_woogie(<?php echo $_product->getId(); ?>);">Buy now </a> / <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"> More details</a>
                </p>
                 <?php if ($_product->isSaleable()): ?>
                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                    <form id="add-to-cart-custom_<?php echo $_product->getId(); ?>" data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                        <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                        <?= $block->getBlockHtml('formkey') ?>
                        <!--<button type="submit"
                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                class="action tocart primary">
                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                        </button>-->
                    </form>
                <?php endif; ?>
            </div>
            
        <?php endforeach; ?>
    </div>
    <?php foreach ($_productCollection as $_product): ?>
        <!-- Modal 1 -->
            <!--<div class="modal fade hidden-xs" id="myModal_<?php echo $_product->getId(); ?>" role="dialog">
                <div class="modal-dialog">
                    
                    <div class="modal-content">
                        <div class="modal-body">
                            img src="<?php echo $_product->getImage('image'); ?>" class="img-responsive center-block">
                            <?= $productImage->toHtml() ?>
                            
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="modal-show" style="display: none;" id="modal-show-<?php echo $_product->getId(); ?>">
                <?= $productImage->toHtml() ?>
            </div>
           <?php 
                $modal_code .= '$("#image-modal-'.$_product->getId().'").click(function() {$("#modal-show-'.$_product->getId().'").modal(options).modal("openModal");});'
           ?>
    <?php endforeach; ?>   
<script type="text/javascript">
    var $ = jQuery.noConflict();
    function add_to_cart_woogie(product_id){
        //alert(product_id);
        $('#add-to-cart-custom_'+product_id).submit(); //.trigger('submit');
    }
</script>
<?php endif; ?>
<a id="ship_now">Click for Ship</a>

<div id="shipNowContent" style="display: none;">
    jbasdask kansodnkoasd knasoda<br/>
    lkkansdnasda
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                //title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            <?php echo $modal_code; ?>
        }
    );
</script>
