<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$button = $block->getAddButton();
$title = $block->getAddTitle();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>


<?php if (!empty($title)) { ?>
    <div class="product-details">
        <h4 class="heading"><?php echo $_product->getName(); ?></h4>
        <?php if ($_attributeValue): ?>
            <div class="named-after full"><?php echo $_attributeValue; ?></div>
        <?php endif; ?>
    </div>
<?php } ?>

<?php if (empty($title)) { ?>
    <?php if ($_attributeValue): ?>
        <div class="named-after short"><?php echo $_attributeValue; ?></div>
    <?php endif; ?>
<?php } ?>

<?php if (!empty($button)) { ?>
    <div class="product-details-right">
        <button type="button" class="btn btn-show-more show-more">Show more...</button>
        <button type="button" class="btn btn-show-more show-less">Show Less...</button>
    </div>
<?php } ?>

<script type="text/javascript">
    var $ = jQuery;
    $('.show-less').hide();
    $('.show-more').click(function() {
        $('.show-less').show();
        $(this).hide();
        $('.short').css("height","100%");
    });
    $('.show-less').click(function() {
        $('.show-more').show();
        $(this).hide();
        $('.short').css("height","50px");
    });
</script>