<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php $data = json_decode($block->getGalleryImagesJson()); ?>

<div class="row">
    <!-- start left column -->
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 product-details-left">
        <?php for ($i=0; $i < count($data); $i++) {  ?>
            <div class="product-img">
                <div>
                    <img src="<?= $data[$i]->img ?>" class="img-responsive center-block" alt="img<?=$i?>">
                </div>
                <a href="#" class="zoom-icon hidden-xs" type="button" data-toggle="modal" data-target="#myModal<?=$i?>">
                    <img src="<?= $block->getViewFileUrl('images/icon-product-zoom.png'); ?>" alt="zoom">
                </a>
            </div>
        <?php } ?>
    </div>
    <!-- end left column -->
</div>

<!-- Modal 1 -->
<?php for ($i=0; $i < count($data); $i++) {  ?>
    <div class="modal fade hidden-xs" id="myModal<?=$i?>" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <div>
                        <img src="<?= $data[$i]->full ?>" class="img-responsive center-block" alt="full_img<?=$i?>">
                    </div>
                    <a type="button" data-dismiss="modal" class="close-btn">
                        <img src="<?= $block->getViewFileUrl('images/icon-popup-close.png'); ?>" alt="close">
                    </a>
                </div>
            </div>
        </div>
    </div>
<?php } ?>