<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!-- <?php $_product = $block->getProduct() ?> -->

<div class="product-social-links">
	<a href="#"><i class="fa fa-facebook"></i></a>
	<a href="#"><i class="fa fa-twitter"></i></a>
	<a href="#"><i class="fa fa-pinterest-p"></i></a>
</div>
<!-- <a href="#"><img src="img/icon-social-small-black.png" alt=""></a> -->

<!-- <?php if ($block->canEmailToFriend()): ?>
    <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action mailto friend"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
<?php endif; ?> -->
