<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<div class="additional-attributes-wrapper yourPhotos" id="yourPhotos">
    <h4>SHARE PHOTOS OR VIDEO</h4>
    <a href="#" class="question-text" data-toggle="modal" data-target="#photoGuideline">
        <img src="<?= $this->getViewFileUrl('images/icon-question-small.png'); ?>"> Photo and video guidelines
    </a>
    <p class="text-light">
        If you would like to share photos or video of  your pet playing with their Woogie Whomper, upload them here. We might post them on this page or in our blog.
    </p>
    <input type="file" id="myFile" placeholder="Choose file">
    <p class="text-bold">
        ...OR... to share a video of your pet playing with their Woogie Whomper (ex: from YouTube), enter the URL here.
    </p>
    <div class="form-group">
        <input type="text" class="form-control place-url" id="" placeholder="">
    </div>
    <p class="text-bold">Write a caption for this photo or video if you like.</p>
    <div class="form-group">
        <textarea class="form-control caption" rows="5" id=""></textarea>
    </div>
    <p class="text-bold">If you'd like an email when your photo is on the site or blog, please enter it here.  Your email address will not be shown in public, and never shared.</p>
    <div class="form-group">
        <input type="email" class="form-control email" id="" placeholder="">
    </div>
    <button type="button" class="btn btn-write-review">UPLOAD PHOTO AND CAPTION</button>
</div>

<div class="block review-add">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Write Your Own Review') ?></strong></div>
<div class="block-content">
<?php if ($block->getAllowWriteReviewFlag()): ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <?php echo $block->getChildHtml('form_fields_before')?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
        <legend class="legend review-legend"><span><?php /* @escapeNotVerified */ echo __("You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend><br />
        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
        <span id="input-message-box"></span>
        <fieldset class="field required review-field-ratings">
            <legend class="label"><span><?php /* @escapeNotVerified */ echo __('Your Rating') ?><span></legend><br/>
            <div class="control">
                <div class="nested" id="product-review-table">
                    <?php foreach ($block->getRatings() as $_rating): ?>
                        <div class="field choice review-field-rating">
                            <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                            <div class="control review-control-vote">
                            <?php $options = $_rating->getOptions();?>
                            <?php $iterator = 1; foreach ($options as $_option): ?>
                                <input
                                    type="radio"
                                    name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                    value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                    class="radio"
                                    data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                    aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                                <label
                                    class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                    for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                    title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                    <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                </label>
                            <?php $iterator++; ?>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </fieldset>
    <?php endif ?>
        <div class="field review-field-nickname required">
            <label for="nickname_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Nickname') ?></span></label>
            <div class="control">
                <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
            </div>
        </div>
        <div class="field review-field-summary required">
            <label for="summary_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Summary') ?></span></label>
            <div class="control">
                <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
            </div>
        </div>
        <div class="field review-field-text required">
            <label for="review_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Review') ?></span></label>
            <div class="control">
                <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit Review') ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?php /* @escapeNotVerified */ echo __('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>

 <!-- Modal Question Guideline -->
    <div class="modal fade" id="photoGuideline" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <a type="button" data-dismiss="modal" class="close-btn">
                        <img src="<?= $this->getViewFileUrl('images/icon-modal-close.png'); ?>">
                    </a>
                    <h4>Photo and video guidelines</h4>
                    <p>
                        We love to see photos and video of pets and their Woogie Whompers, so first of all thanks for sharing! Please make sure your photos or video are relevant to this product. We might post your photo or video on this page or on our blog. We will let you know when we'hv posted it if you include your email address. When writing your caption, please use English.
                        <br><br>
                        We reserve the right to not post your photo or video if it contains any of the following types of content or violates other internal guidelines:
                        <br>
                    </p>
                    <ul>
                        <li>Full name, email addresses, URLs, phone numbers, physical addresses or other forms of contact information</li>
                        <li>Obscenities, discriminatory language, or other language not suitable for a public forum</li>
                        <li>Advertisements, "spam" content, or references to other products, offers, websites, or promotional details or services</li>
                        <li>Critical or spiteful comments</li>
                    </ul>
                    <p>
                        Photo questions? Please contact us at 281-610-8631 or feedback@woogiewhomper.com
                    </p>
                </div>
            </div>
        </div>
    </div>